### PR TITLE
Itrombley/update 2.1.3

### PR DESCRIPTION
**Pull request by itrombley**
Update to v 2.1.3.

### CODE REVIEW

**Review by chri7325 — COMMENTED** [review]
Changes look good but can the interim commits be squashed together before merging? This will reduce the amount of noise next time we do an upgrade and want to check back at our changes. Can the commits that are changing config files also get a good reason why so we can understand what the change is doing. This will make it easier for anyone to upgrade later.

**Comment by itrombley** [comment]
Yeah, let me work on that.

**Comment by itrombley** [comment]
@chri7325, Do you want me to squash all the commits or just mine?

**Comment by chri7325** [comment]
@itrombley just yours. We don't want to change the history for theirs so we can always merge in future updates.

**Comment by itrombley** [comment]
Ok. I think the best thing to do is close this PR, recreate the branch, apply the changes in one commit and then make a new PR.

**Comment by chri7325** [comment]
@itrombley I would actually just reopen this PR, do an interactive rebase locally to squash the commits into one, then you can ammend that commit to give it some details and force push the branch. That makes the work a lot more trivial.

**Pull request closed without merging**
